/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/slurm/slurm_sim_ws/slurm_opt/lib/slurm";
char *default_slurm_config_file = "/home/slurm/slurm_sim_ws/slurm_opt/etc/slurm.conf";
char *default_plugstack = "/home/slurm/slurm_sim_ws/slurm_opt/etc/plugstack.conf";
